In [5]:
import numpy as np
import pandas as pd
import os

In [2]:
def calcLengthOfBody(row, excluded_columns):
  x_values = [val for columnName, val in row.items() if (columnName not in excluded_columns) and (columnName.find('_X')!=-1)]
  y_values = [val for columnName, val in row.items() if (columnName not in excluded_columns) and (columnName.find('_Y')!=-1)]
  len_X = max(x_values) - min(x_values)
  len_Y = max(y_values) - min(y_values)
  return len_X, len_Y

In [3]:
def normalize(row):
    row_df = pd.DataFrame(row).transpose()
    excluded_columns = ['center_X','center_Y','ID', 'NAME', 'Scale', 'Activity', 'Category']
    lenBody_X, lenBody_Y = calcLengthOfBody(row, excluded_columns)
    for column in row_df.columns:
        if column not in excluded_columns:
            if (column.find('_X') != -1) and (row_df[column]!=-1).all():
                row_df[column] = (row_df[column] - row_df['center_X'])/lenBody_X
            if (column.find('_Y') != -1) and (row_df[column]!=-1).all():
                row_df[column] = (row_df[column] - row_df['center_Y'])/lenBody_Y

    return row_df.squeeze()

In [24]:
df = pd.read_csv("../data/original_annotations.csv")
df.drop(columns = ['ID', 'Scale', 'Category'], inplace = True)
print(df.shape)
keptImages = os.listdir('../data/classification_images')
#filter to only include the images I picked
df = df[df['NAME'].isin(keptImages)]
print(df.shape)
df_extra = pd.read_csv("../data/df_extra.csv")
df_combined = pd.concat([df, df_extra], ignore_index=True)
print(df_combined.shape)
df_normalized = df_combined.apply(normalize, axis = 1)

(843, 37)
(374, 37)
(385, 37)

In [25]:
nan_locations = df_combined.isna()
nan_locations

,Unnamed: 0,NAME,r ankle_X,r ankle_Y,r knee_X,r knee_Y,r hip_X,r hip_Y,l hip_X,l hip_Y,...,r shoulder_Y,l shoulder_X,l shoulder_Y,l elbow_X,l elbow_Y,l wrist_X,l wrist_Y,Activity,center_X,center_Y
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
381,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
382,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
383,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
384,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
df_normalized.columns

Index(['Unnamed: 0', 'NAME', 'r ankle_X', 'r ankle_Y', 'r knee_X', 'r knee_Y',
       'r hip_X', 'r hip_Y', 'l hip_X', 'l hip_Y', 'l knee_X', 'l knee_Y',
       'l ankle_X', 'l ankle_Y', 'pelvis_X', 'pelvis_Y', 'thorax_X',
       'thorax_Y', 'upper neck_X', 'upper neck_Y', 'head top_X', 'head top_Y',
       'r wrist_X', 'r wrist_Y', 'r elbow_X', 'r elbow_Y', 'r shoulder_X',
       'r shoulder_Y', 'l shoulder_X', 'l shoulder_Y', 'l elbow_X',
       'l elbow_Y', 'l wrist_X', 'l wrist_Y', 'Activity', 'center_X',
       'center_Y'],
      dtype='object')

In [21]:
df_normalized

,Unnamed: 0,NAME,r ankle_X,r ankle_Y,r knee_X,r knee_Y,r hip_X,r hip_Y,l hip_X,l hip_Y,...,r shoulder_Y,l shoulder_X,l shoulder_Y,l elbow_X,l elbow_Y,l wrist_X,l wrist_Y,Activity,center_X,center_Y
0,80.0,024929223.jpg,-0.574074,0.423932,-0.365320,0.198453,-0.119529,-0.039382,0.119529,0.039382,...,-0.440920,0.321549,-0.317370,0.425926,-0.081080,0.393939,0.051737,"skiing, downhill",571.0,655.5
1,125.0,048945276.jpg,0.041605,0.579925,-0.102122,0.305294,-0.253415,-0.009332,0.253415,0.009332,...,-0.230637,0.049170,-0.283964,0.397143,-0.155980,-0.124816,-0.094655,hacky sack,638.5,273.5
2,127.0,067213555.jpg,-0.068627,0.202517,-0.470588,0.053776,-0.034314,-0.012586,0.034314,0.012586,...,-0.305492,-0.235294,-0.266590,-0.377451,-0.145309,-0.441176,-0.223112,hacky sack,645.0,320.5
3,128.0,023763754.jpg,0.293750,0.514720,0.193750,0.289089,0.181250,-0.009871,-0.181250,0.009871,...,-0.289089,-0.043750,-0.258065,-0.106250,-0.063459,-0.443750,0.080381,hacky sack,1224.5,493.5
4,132.0,004077514.jpg,0.089947,0.175781,-0.328042,-0.045573,-0.116402,-0.011719,0.116402,0.011719,...,-0.253906,0.179894,-0.227865,0.322751,-0.100260,0.476190,-0.001302,hacky sack,158.0,191.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"softball, general",NaN,NaN
392,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"softball, general",NaN,NaN
393,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,track and field,NaN,NaN
394,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,track and field,NaN,NaN
395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,track and field,NaN,NaN

In [28]:
#won't be considering frisbee and lacrosse
ignoreList = ['frisbee', 'lacrosse', 'rollerblading', 'track and field']
df_normalized = df_normalized[~df_normalized['Activity'].isin(ignoreList)]
final_exclusion = df_normalized.drop(columns = ['Unnamed: 0','NAME', 'center_X', 'center_Y'])

In [29]:
final_exclusion.to_csv('../data/normalized_annotations_final.csv', index=False)

In [30]:
final_exclusion['Activity'].value_counts()

Activity
rowing, stationary                                       71
golf                                                     56
basketball                                               41
bowling                                                  28
skiing, downhill                                         27
skateboarding                                            26
softball, general                                        26
boxing                                                   24
hacky sack                                               23
soccer                                                   17
tennis, hitting balls, non-game play, moderate effort    14
football                                                 13
Name: count, dtype: int64

In [20]:
nan_locations = final_exclusion.isna()
nan_locations

,r ankle_X,r ankle_Y,r knee_X,r knee_Y,r hip_X,r hip_Y,l hip_X,l hip_Y,l knee_X,l knee_Y,...,r elbow_Y,r shoulder_X,r shoulder_Y,l shoulder_X,l shoulder_Y,l elbow_X,l elbow_Y,l wrist_X,l wrist_Y,Activity
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
392,True,True,True,True,False,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
393,True,True,True,True,False,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
394,True,True,True,True,False,False,False,False,True,True,...,True,False,False,True,True,True,True,True,True,False
395,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False